// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function BuildApp(arg1) {
  return window['go']['main']['App']['BuildApp'](arg1);
}

export function CancelBuild() {
  return window['go']['main']['App']['CancelBuild']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function GetDistInfo(arg1) {
  return window['go']['main']['App']['GetDistInfo'](arg1);
}

export function ImportFromPaths(arg1, arg2) {
  return window['go']['main']['App']['ImportFromPaths'](arg1, arg2);
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenDistFolder() {
  return window['go']['main']['App']['OpenDistFolder']();
}

export function OpenIconFile() {
  return window['go']['main']['App']['OpenIconFile']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function OpenSignPfxFile() {
  return window['go']['main']['App']['OpenSignPfxFile']();
}

export function OpenTempFolder() {
  return window['go']['main']['App']['OpenTempFolder']();
}

export function RunOutput(arg1) {
  return window['go']['main']['App']['RunOutput'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}

export function TestProxyTarget(arg1) {
  return window['go']['main']['App']['TestProxyTarget'](arg1);
}

export function UploadDistZip(arg1) {
  return window['go']['main']['App']['UploadDistZip'](arg1);
}

export function ValidateIcon(arg1) {
  return window['go']['main']['App']['ValidateIcon'](arg1);
}
