// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appconf} from '../models';
import {selfupdate} from '../models';

export function AppVersion():Promise<string>;

export function ApplyUpdate(arg1:string):Promise<string>;

export function BuildApp(arg1:appconf.BuildConfig):Promise<void>;

export function CancelBuild():Promise<void>;

export function CheckUpdate():Promise<selfupdate.Info>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportProfile(arg1:string):Promise<string>;

export function GetDistInfo(arg1:string):Promise<appconf.DistInfo>;

export function ImportFromPaths(arg1:string,arg2:Array<string>):Promise<string>;

export function ImportProfile():Promise<string>;

export function ListProfiles():Promise<Array<string>>;

export function LoadProfile(arg1:string):Promise<appconf.BuildConfig>;

export function LoadSettings():Promise<appconf.BuildConfig>;

export function OpenDistFolder():Promise<string>;

export function OpenIconFile():Promise<string>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function OpenSignPfxFile():Promise<string>;

export function OpenTempFolder():Promise<string>;

export function RunOutput(arg1:string):Promise<void>;

export function SaveProfile(arg1:string,arg2:appconf.BuildConfig):Promise<string>;

export function SaveSettings(arg1:appconf.BuildConfig):Promise<void>;

export function SelectOutputPath(arg1:string):Promise<string>;

export function TestProxyTarget(arg1:string):Promise<string>;

export function UploadDistZip(arg1:string):Promise<string>;

export function ValidateIcon(arg1:string):Promise<string>;
